kind: ApplicationSet
apiVersion: argoproj.io/v1alpha1
metadata:
  name: kyverno
  namespace: argocd
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          clusterType: tenant        
  template: 
    metadata:
      name: '{{name}}-kyverno'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
    spec:
      project: "default"
      source:
        repoURL: https://github.com/nirmata/demo-repository
        targetRevision: HEAD
        path: ack-gitops-kyverno/addons/kyverno
      destination:
        server: '{{server}}'
        namespace: kyverno
      syncPolicy:
        syncOptions:
        - Replace=true
        automated:
          selfHeal: true  
        retry:
          limit: 30
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m0s
